version: '3'

services: 
  s1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "5432:5432"
  s2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "5433:5432"
  s3:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "5434:5432"
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - s1
      - s2
      - s3
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5555:80"